### ISSUE TITLE
Добавление на f-droid.org

### ISSUE THREAD

**Issue by OmlineEditor** [vladpen/cams#1]
Почитала статью на хабре. Хорошее приложение, спасибо за него.
Для улучшения идей и улучшения функционала вы можеет добавить приложение в каталог на сайте f-droid.org?
Это привлечет пользователей и разработчиков которые смогу помочь в развитии приложения.

**Comment by vladpen** [comment]
Да, конечно. F-droid ведь поддерживает ссылки на гитхаб, верно?

**Comment by OmlineEditor** [comment]
да, с этим проблем нет, ссылки поддерживает с любого места.
Главное чтобы была лицензия по которой распространяется прога и исходные коды без всяких зависимостей из которых они сами будут собирать прогу. Вот тут коротко что нужно делать: https://habr.com/ru/company/ruvds/blog/518350/

**Comment by OmlineEditor** [comment]
Поздравляю в выпуском на f-droid, я вам там уже паписала несколько пожеланий.
И можно еще добавить в писание вашей прогрммы ссылку на страницу f-droid где ваша програмка опубликована?
