### ISSUE TITLE
Добавить кнопку выключения звука для камер с микрофоном

### ISSUE THREAD

**Issue by OmlineEditor** [vladpen/cams#10]
Прошу добавить возможность выключить звук полностью для камер со встроенным микрофоном. Например кнопка в углу экрана. Щас звук можно выключить если убрать громкость полностью, но при этом страдаеют другие звуки т.к. громкость меняется во всем телефоне.

![mute](https://user-images.githubusercontent.com/13348933/160445367-0d983476-4fec-40b7-8d2f-39cc5ae31249.png)

**Comment by vladpen** [comment]
Выполнено.
