### ISSUE TITLE
Два RTSP адреса для двух разных потоков от одной камеры

### ISSUE THREAD

**Issue by OmlineEditor** [vladpen/cams#14]
В камерах есть возможность транслировать два разных потока:
- первичный поток в максимальном качестве
- вторичный потом в более низком качестве

Прошу сделать возможность указывать для одной камеры два разных RTSP адреса для разных потоков. Потом при просмотре камеры эти потоки хотелось бы переключать.
В углу будет кнопочка ключить высокое качество или просто кнопка выбор типа потока 1й или 2й.

**Comment by asonukhan** [comment]
Hi

**Comment by vladpen** [comment]
Поддержка двухканальных камер уже на гитхабе (войдет в 1.3.5).
Усложнять настройки не вижу смысла, второй поток просто всегда используется в группах (если указан).

**Comment by OmlineEditor** [comment]
> Усложнять настройки не вижу смысла, второй поток просто всегда используется в группах (если указан).

несколько вопросов:
1) Второй поток всегда по умолчанию в группе и ничего дополнительно не нужно выбирать? верно?
2) При клике на камеру в группе или при открытии одиночной камеры из общего списка по умолчанию **ВСЕГДА** открывается первый поток? верно?
3) нет настроек выбора потока для посмотра одиночной камеры, нельзя переключить при просмотре тип потока вообще никак. верно?
4) по умолчанию можно выбрать **_всегда_** смотреть 2й потом в худшем качестве и только по запросу при посмотре переключить на первый потом в максимальном разрешении?

**Comment by vladpen** [comment]
Все верно. Если указаны потоки, то мелкие картинки (в группе) показываются в низком разрешении, крупные - в высоком.

На практике большого смысла экономить что-либо для одного стрима нет, тем более, что 99% камер находятся в локальных сетях. В группе по предварительной прикидке на вторых каналах можно получить снижение нагрузки процентов до 20-ти (или, другими словами, показывать на 20% больше камер). Это имеет смысл, если не пользоваться зумом в группе.

**Comment by OmlineEditor** [comment]
Вот этого я и боялась, есть подводные камни в вашем типе настройки, вот тут смотрите: https://github.com/vladpen/cams/issues/44

**Comment by vladpen** [comment]
Добавлен переключатель К1/К2 согласно [#44](https://github.com/vladpen/cams/issues/44).
