### ISSUE TITLE
Импорт и экспорт настроек

### ISSUE THREAD

**Issue by OmlineEditor** [vladpen/cams#15]
Настройки хранятся глубоко в недрах программы и их без root прав нельзя сохранить и перенести. 
А руками занова всё вбивать долго. Лучше именть возможноть экспортировать настроки и импортировать.

**Comment by vladpen** [comment]
Добавлено в 1.2.2.

Обратите внимание, что пароли зашифрованы и в другой установке их нужно перебивать руками (это не баг).

**Comment by OmlineEditor** [comment]
Что значит другой установке ?
Если я на своем телефоне сброшу все настройки на заводские и занова постявлю программу, мне нужно занова вводить пароли или нет?

**Comment by OmlineEditor** [comment]
Это очень не удобно и страдает сама функция экспорта и ее смысл.
При экспорте 1-3 камер можно пережить ввод одно и того же пароля, но если камер 20 и везде разные пароли тогда это мрак.
Давайте тогда сдалем так, просто сделаем два вариант экспорта:
- экспорт без паролей в простой текстовый файл (только ссылки на камеры их название и группа куда она входит)
- экспорт полных данных включая логин и пароль, но при этом экспорте файл шифруется и требует ввести пароль для шифрования экспортированны данных. Чтобы предотвратить взлом и брутфорс пароля можно шифровать не 1 раз данные, а 2 млн. раз как это сделано в keepass (там есть такая настройка) см. скрин внизу:


![изображение_2022-05-17_140713](https://user-images.githubusercontent.com/13348933/168797411-1a2c64c0-0468-41db-8f9f-538388439ceb.png)

**Comment by vladpen** [comment]
Тогда предлагаю считать выполненным первый пункт. Второй сделаю позже.

**Comment by OmlineEditor** [comment]
Хорошо, согласна. Я новый тикет сделала чтобы вам было проще ориентировться и не забыть.
