### ISSUE TITLE
Просмотр несколько камер одновременно

### ISSUE THREAD

**Issue by OmlineEditor** [vladpen/cams#16]
Прошу сделать возможность смотреть одновременно несколько разных камер в одном окне. 
Создается сетка нужного размера (2x2, 2x3, 1x3, 3x3 и т.д.) и в нее добавляются нужные камеры и можно их смотреть на одном экране одновременно.

![3](https://user-images.githubusercontent.com/13348933/160871055-e5848e2e-1989-4060-8c83-93c36149856e.png)

**Comment by OmlineEditor** [comment]
Еще при клике на камеру хочется чтобы камера развернулась на весь экран и можно было бы посмотреть максимально детально.

Этот режим посмотра нескольких камер навверное будет самый часто использвемый, поэтому прошу добавить в настройки опцию: при открытии программы сразу начать воспроизведение посднего варианта камер без показа меню с камерами. Нет смысла жать на вариант выбора одного и того же варианта камер каждый раз при открытии программы.

**Comment by vladpen** [comment]
Группы добавлены в 1.2.0

**Comment by vladpen** [comment]
Пока нет. Это приложение ориентировано на смартфон, там больше 4-х камер уже просто не видно ничего.

**Comment by OmlineEditor** [comment]
Ну есть же еще и планшеты, там экраны большие. Как раз для них 3х3 камеры на экране самое то.
Может на досуге подумаете реализовать более 4 камер?

P.S. Я на телефоне у себя пробовала смотреть 3х3 камеры вы правы мелко, но это лучше чем полное отсутствие каких-то камер.
