### ISSUE TITLE
Нет автообновления на f-droid

### ISSUE THREAD

**Issue by OmlineEditor** [vladpen/cams#18]
Вы выложили программу на сайт f-droid, но при этом не установили автообновление. В настройках в файле https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.vladpen.cams.yml прописано:
AutoUpdateMode: None
UpdateCheckMode: None

прошу сделать автообновление, чтобы f-droid все делал сам без вашего участия.
И вам проще и пользователям лучше.

**Comment by vladpen** [comment]
Это было связано с CI/CD f-droid'a - он не умеет обновлять apk для разных платформ. Договорились публиковать только arm64, но зато автоматически.
