### ISSUE TITLE
Перестал работать 2й поток на всех камерах

### ISSUE THREAD

**Issue by OmlineEditor** [vladpen/cams#22]
В самой первой версии работал 2й потом в худшем качестве (просто обзорный поток).
1й поток на всех камерах работает как обычно, 2й перестал совсем. проверенно на 3х разных камерах.
При запуске 2го потока еще на экрне замечены артефакты в виде квадратов появляющихся на несколько миллисекунд.

В логах ошибки libvlc, сам лог приложила:
[log_cam.txt](https://github.com/vladpen/cams/files/8514843/log_cam.txt)

**Comment by vladpen** [comment]
Спасибо за отчеты об ошибках.

В текущей версии (см. последний коммит) воспроизвести ошибку не удалось, можете проверить на ваших камерах? Возможно, стоит очистить кеш или проверить на новой установке.

**Comment by OmlineEditor** [comment]
Хорошо, я отпишусь когда протестирую новую версию, через пару дней должна появится на f-droid.

**Comment by vladpen** [comment]
Нужно больше данных:

1. Воспроизводится ли этот поток в другом плеере на этом же устройстве?
2. Воспроизводится ли этот поток на других устройствах (включая стационарные ПК)?

URL камеры нужно точно скопировать из настройки камеры (кроме пароля).
Также вы не написали, работает ли поток на новой установке.

**Comment by OmlineEditor** [comment]
В версии 1.1.4 2й поток не работал, Жду новую версию 1.2.0
в другом плеере (например VLC) 2й поток с нужной мне камеры работает и на ПК тоже работает без проблем.
URL я точно вставила.
----
Попробовала удалить все камеры и занова вбить все настройки, заработали 2 камеры, но 1 камера как не работала так и не работает.

**Comment by vladpen** [comment]
Еще неплохо бы попробовать на новой установке (или установить приложение на другом телефоне).

Если не поможет, нужно попробовать уменьшить параметр "network-caching" где-то до 150 мс (это строка addOption(":network-caching=150")) в файлах VideoActivity и GroupActivity.

Если хотите, могу собрать APK для теста [тут](https://github.com/vladpen/cams/blob/main/app/release/app-arm64-v8a-release.apk).

**Comment by OmlineEditor** [comment]
Где эти файлы лежат (VideoActivity и GroupActivity)? И для чего уменьшать network-caching где-то до 150 мс, в чем физический смысл?

**Comment by vladpen** [comment]
1. app/src/main/java/com/vladpen/cams/
2. Кеширование - единственный реальный способ ускорения начальной загрузки потока. Слишком низкое значение может привести к отсутствию ключевого кадра в кеше (визуальный эффект - серые квадраты), слишком высокое - к срыву потока (теоретически).

Нужно проверить (на моих камерах работает).

**Comment by OmlineEditor** [comment]
Кажется я нашла проблему и она не в кэше, а в пароле точней в его неверной обработке.
Если создать нового пользователя с простым паролем, на той самой неработающей камере, тогда все нормально, а вот если в пароле есть спец символы тогда ваша программа не верно понимает их.
попробуйте создать у себя пользователя и задать ему пароль:
`a:b*d@d.Z+c/qf>t`

Поэтому прошу сделать отдельное поле для ввода пароля, так программа будет точно знать где пароль  https://github.com/vladpen/cams/issues/2
И при подключении не будет утекать пароль, т.к. он будет отдельно передан в потоке https://github.com/vladpen/cams/issues/24

**Comment by OmlineEditor** [comment]
Еще одно замечание, вы в версии 1.1.4 сделали замену способа хранения пароля (зашифровали его), похоже при переходе и обновлении версий конвертация пароля тоже немного хромает и неверно работает, это тоже прошу учесть.

**Comment by vladpen** [comment]
Исправлено в 1.2.2
