### ISSUE TITLE
Сокрытие строки с названием камеры при клике

### ISSUE THREAD

**Issue by OmlineEditor** [vladpen/cams#23]
Сейчас в программе через несклько секунд исчезает строка с названием камеры, стало удобнее, спасибо.
Можно добавить функцию чтобы строка исчезала еще при клике на экран? Сейчас при клике на экран строка только появляется, но не исчезает если кликнуть повторно.

**Comment by vladpen** [comment]
В последнем коммите улучшена логика поведения видеопанелей: они не появляются при масштабировании и перетаскивании, только при явном тапе. Такое поведение логично - пользователь, скорее всего, будет именно вызывать панели, например, чтобы остановить воспроизведение или сделать снимок. Не вижу смысла менять это ради случайного касания экрана.

**Comment by OmlineEditor** [comment]
На вид, логично. Сейчас при мастабировании и клике строка с названием камеры появляется, я подожду новую версию.
