### ISSUE TITLE
Экспорт данных с шифрованием

### ISSUE THREAD

**Issue by OmlineEditor** [vladpen/cams#25]
Прошу сделать экспорт полных данных включая логин и пароль, но при этом экспорте файл шифруется и требует ввести пароль для шифрования экспортированны данных.

**Comment by vladpen** [comment]
Сухой остаток: добавлен пароль на экспорт/импорт, при этом файл текстовый, его можно читать (кроме паролей, конечно)

**Comment by OmlineEditor** [comment]
А нам пароли только и нужно зашифровать. Главная задача выполенна.
