### ISSUE TITLE
Удаление камеры в группе с визуализацией

### ISSUE THREAD

**Issue by OmlineEditor** [vladpen/cams#26]
Прошу сделать более удобный и понятный способ удаления камеры из группы. Я понимаю что ее можно удалить просто потащив в бок, но это не понятно и не очевидно.
- нужна визуализация удаления камеры (когда тащим камеру в бок появляется красный фон под надписью или фон с мусорным ведром например)
- для того чтобы было понятно как удалять камеру из списка внизу под кнопкой сохранить можно добавить серым едва заметным текстом подсказку.

**Comment by vladpen** [comment]
Выполнено в 1.3.0
