### ISSUE TITLE
Работает не вся строка для клика

### ISSUE THREAD

**Issue by OmlineEditor** [vladpen/cams#3]
Если кликать на название камеры то камера открывается и работает, если кликать на пустую строку рядом с названием то ничего не работает и камера не открывается. Иными словами поле для клика это только название камеры. Это нормально если экран маленький и строка длинная, а если это короткие названия на планшете тогда трока попросту пустует без дела и не работает.
Прошу сделать возможность кликать на любое место в строке чтобы открыть камеру для просмотра.
![screens](https://user-images.githubusercontent.com/13348933/160436283-13ab397c-0ef4-4983-8ba5-b5afebef8709.png)

**Comment by vladpen** [comment]
Большое спасибо за обратную связь и отчеты об ошибках. Выполнено.
