### ISSUE TITLE
No support for ubiquiti rtsp or rtsps

### ISSUE THREAD

**Issue by hakarune** [vladpen/cams#32]
Ubiquiti rtsp doesn't work. Url: rtsp://10.1.1.1:7441/Tl0gBn9i2efNddA0

Rtsps url
rtsps://10.1.1.1:7441/Tl0gBn9i2efNddA0?enableSrtp

**Comment by vladpen** [comment]
Can you provide temporary access to the camera for testing (with a white IP address?

Does the VLC player can play the stream on this or another device?

**Comment by hakarune** [comment]
> Can you provide temporary access to the camera for testing (with a white IP address?
> 
> Does the VLC player can play the stream on this or another device?

Unfortunately they're local only cameras. VLC plays the rtsp  url without issue. Haven't tried the Rtsps on VLC.  I tested tinyCam as well it plays them without issue as well.

**Comment by vladpen** [comment]
Can you provide a snippet of the application log with the failed connection attempt?
Also, please tell me the model of your camera.

**Comment by vladpen** [comment]
No response

**Comment by hakarune** [comment]
> Can you provide a snippet of the application log with the failed connection attempt?
> Also, please tell me the model of your camera.

How do I get the log?

And it's 3 different ubiquiti Unifi cameras. (doorbell, the cheap $29 wifi, and the G3 dome)

**Comment by hakarune** [comment]
> No response

Sorry, the github app didn't notify me of the new response

**Comment by vladpen** [comment]
> How do I get the log?

Version 1.3.2 has such functionality.

> doorbell, the cheap $29 wifi, and the G3 dome

Thanks.

**Comment by vladpen** [comment]
No response.
