### ISSUE TITLE
пароль при экспорте водить дважды

### ISSUE THREAD

**Issue by OmlineEditor** [vladpen/cams#33]
Прошу сделать возможность водить пароль при экспорте данных дважды, чтобы точно убедится что он имено такой какой я хочу. Сейчас только 1 раз вводится и есть вероятность что при ошибке ввода в 1 букву будут проблемы.

**Comment by OmlineEditor** [comment]
И еще вспомнила, в поле для ввода почему-то первая буква всегда большая, как будто это поле не для пароля, а для простого предложения. Можно убрать эту опцию чтобы пароль всегда был с маленький быквы?

**Comment by vladpen** [comment]
Проверил на эмуляторе и двух телефонах - у меня ввод начинается с маленькой буквы. Все настройки по умолчанию.

**Comment by OmlineEditor** [comment]
Для поля пароля у вас есть дополнительные опции которые передаются клавиатуре?
Например в пароле для системы у меня маленькие буквы, в KeepassDX тоже маленькие буквы, а у вас большие почему-то.
Ну если ничего не найдет с параметрами ничего страшного, вроде не смертельная ошибка.

**Comment by vladpen** [comment]
Нет, никаких опций, все по дефолту.
Подтверждение реализовано в 1.3.1.
