### ISSUE TITLE
Имя файла при экспорте с датой и временем

### ISSUE THREAD

**Issue by OmlineEditor** [vladpen/cams#34]
сайчас при экспорте в файл настроек сохраняются в файле "cams". Для удобства лучше сделать имя файла еще и с датой и временем: "cams_YYYY-MM-DD_HH-mm-ss"

**Comment by vladpen** [comment]
В системный диалог помещается только camsYYMMDD, остальное пользователю не видно (по крайней мере, на телефоне так). Реализовано в 1.3.1.
