### ISSUE TITLE
При запуске программы требует ввести адрес камеры 

### ISSUE THREAD

**Issue by OmlineEditor** [vladpen/cams#35]
Удалила программу, ставлю ее занова и она при первом запуске  **_требует_** ввести имя камеры и ее адрес камеры.
А должна показывать **_основное окно программы_** где можно добавить камеры или импортировать настройки.

**Comment by vladpen** [comment]
Это не баг, а фича. Пустой главный экран выглядит крайне странно и для пользователя, впервые запустившего приложение, выглядит как косяк. Предложение ввести первую камеру помогает ему сориентироваться.

Но вот про импорт я, действительно, забыл. Вернул возможность перейти на главный экран (исправление войдет в 1.3.1).

**Comment by vladpen** [comment]
Согласен, так понятней. Вошло в 1.3.1.
