### ISSUE TITLE
Копирование камеры

### ISSUE THREAD

**Issue by OmlineEditor** [vladpen/cams#36]
Если есть ресивер и туда добавляется по одной камере постепенно, то новые камеры будут иметь все теже настройки что и дургие камеры, разницы только в одной цифре - т.е. номере камеры подключенной к ресиверу.
Было бы очень удобно имеющуюся камеру скопировать и поменять там только одну цифру чем вбивать все настройки занова.

Открываешь камеру и жмешь в меню кнопку скопировать камеру, даешь новое название и меняешь одну цифру в номере камеры, очень просто и быстро.

**Comment by vladpen** [comment]
Что мешает сделать ровно то же самое штатным копированием поля адреса, зачем изобретать велосипед?

**Comment by OmlineEditor** [comment]
Проблема будет при вводе пароля, его нельзя скопировать из готовой камеры просто так. Пароль скрыт и его приходится вводить занова, а это неудобно. Кнопка попирования облегчит процедуру.

**Comment by vladpen** [comment]
Выполнено, код на гитхабе.

**Comment by OmlineEditor** [comment]
Не работает, камера на копируется и не появляется в списке. Просто при нажатии на кнопку копировать ничего не происходит. Исправьте проблему.

**Comment by vladpen** [comment]
Работает, на экране добавления камеры вместо "копировать" есть кнопка "вставить".

**Comment by OmlineEditor** [comment]
И как я об этом должна догадаться? Это явно не интуитивно понятный интерфейс.
Зачем эти лишние действия (копировать, выйти в меню, нажать кнопку создать камеру, вставить)?
прошу или переделать логику работы:
- сразу после нажатия кнопки в списке появляется новая камера и я сразу начинаю менять ее настройки, на экране появляется сообщение: "Вы создали дубликат камеры, укажите новое название и поменяйте настройки".

**Comment by vladpen** [comment]
Вставка по кнопке "копировать" противоречит здравому смыслу.

**Comment by OmlineEditor** [comment]
Поэтому я прошу заменить кнопку на **_Скопировать камеру_** Если хотите замените на _**Сделать копию камеры**_
