### ISSUE TITLE
Логи перенести в основное меню и сделать их сохранение

### ISSUE THREAD

**Issue by OmlineEditor** [vladpen/cams#37]
Логи вы спрятали так что их не удобно искать и смотреть и сохранить нельзя их
Может для удобства их перенести в оcновное меню?
Еще я вижу логи но скопировать их оттуда и передать вам для анализа я не могу, могу только скрины делать что неудобно.

Нужно сделать более дружелюбный интерфейс.

**Comment by vladpen** [comment]
Копирование логов в буфер обмена добавлено в 1.3.3.
Выносить выше не вижу смысла, для среднего пользователя это бесполезная информация.
