### ISSUE TITLE
Проблемы со звуком при запуске

### ISSUE THREAD

**Issue by OmlineEditor** [vladpen/cams#40]
Запускаю приложение, открываю камеру.
Вижу знак 🔇 что звук выключен, звука быть в теории не должно, но в реальности я слышу звук с камеры.
Я тыкаю на кнопочку чтобы включить звук, значек меняется на 🔈 звук есть, все норм
Я тыкаю на кнопочку еще раз чтобы выключить звук, значек меняется на 🔇 звук пропадает,  вот щас все норм.

При запуске приложения показан знак 🔇 что звука нет, но это не так, нужно выключать звук

**Comment by OmlineEditor** [comment]
Иногда бывает так что я переключаю звук пытаюсь его выключить, но он все равно работает при любом положении ползунка.

**Comment by vladpen** [comment]
Исправлено в 1.3.3.
