### ISSUE TITLE
Просмотр более 4 камер за 1 раз

### ISSUE THREAD

**Issue by OmlineEditor** [vladpen/cams#41]
У меня на планшете можно без проблем смотреть 6 и даже 9 камер. Я проверяла это на "zero chanel" с ресивера когда можно разом показать 9 камер разом. Для общего понимания размера хватает, ну т.е. понять ходит там кто-то или нет. К тому же на камерах можно включить двойное VCA чтобы подсвечивать движущиеся объекты. Проблем с просмотром большого числа камер на относильтельном маленьком экране планшета нет, думаю и не будет проблем и на телефоне. Многие программы без проблем могут показывать 2x3, 3x3 или 2x4 камеры. Я понимаю что это мелкое изображение будет но это лучше чем будет отсутствовать часть камер вообще.

Прошу добавить возможность смотреть более 4 камер за 1 раз (группы с 12 камерами максимум, т.е. 3x4 аксимум думаю должно хватить для всех групп пользователей)

**Comment by vladpen** [comment]
Проблема тут не только в маленьком размере. Обслуживание потока требует ресурсов процессора, что на слабых устройствах может приводить к значительному снижению отзывчивости интерфейса. Среднестатистический пользователь не будет разбираться, почему тормозит, а начнет ругать программу. Ну, вы же знаете, как это бывает)

**Comment by vladpen** [comment]
Неограниченные группы реализованы в 1.3.4.
Ручная установка сетки не имеет смысла, программа вычисляет оптимальное расположение автоматически.
На этом же экране можно сортировать и удалять камеры.
Поддержки двухканальных камер пока нет (точнее, каждый канал пока считается отдельным потоком).

**Comment by OmlineEditor** [comment]
> Неограниченные группы реализованы в 1.3.4.

Отлично, спасибо !

> Поддержки двухканальных камер пока нет (точнее, каждый канал пока считается отдельным потоком).
Пусть пока так, через время я думаю вы сможеет реализовать эту функцию с двумя потоками, Главное сделать, а потом всю жизнь пользоваться.
