### ISSUE TITLE
Перемещение камер в группе в момент просмотра видео

### ISSUE THREAD

**Issue by OmlineEditor** [vladpen/cams#42]
Прошу предусмотреть возможность перемещать камеры просто нажав пальцем в группе в момент простотра видео перетащив в другое место камеру. Пустые камеры которые ничего не показывают, пустые места, жалательно тоже таскать. Это будет актуально в этом режиме: https://github.com/vladpen/cams/issues/41

**Comment by vladpen** [comment]
Жесты в группах уже задействованы в 1.3.3 для увеличения, сдвига и перехода на экран камеры.

**Comment by OmlineEditor** [comment]
Кликнуть на камеру в момент просмотра в группе - ЕСТЬ. откроется камера.
В момент просмотра камеры увеличить часть изображения жестом - ЕСТЬ.
Переместить камеру в другое место (выше ниже или в другое место если будет 3x3 камеры) в момент просмотра в группе - НЕТУ. Я просила имено это. Прошу открыть тикек т.к. этого нет.

**Comment by vladpen** [comment]
Кажется, мы друг друга не поняли. Жест перемещения используется для того, чтобы двигать увеличенную картинку, поэтому повесить на него другой функционал не получится. Я что-то упустил?

**Comment by OmlineEditor** [comment]
Да вы упустили или я не верно выразилась. Ничего страшного, щас еще раз разберем.
Если смотреть не одну камеру, а **_группу_** камер, там жестов нет, там толко есть клики. Кликаешь на камеру одну из 4х и она открывается и вот в открытой **_одной камере есть жесты_**. А я говорила за **_группу_** камер, там где их разом 4 шт. показываются. Вот там в **_группе_** нет возможности перенести камеру с места на место или поменять ее местами с другой. Так понятно выразилась?

Сделаете в группе перемещение камер?

**Comment by vladpen** [comment]
Начиная с 1.3.3 в группах есть жесты)

**Comment by OmlineEditor** [comment]
А вот не работают жесты. 
Я открыла группу из 4 камер, они все показывают картинку и я хочу переместить одну из них в другое место но не получается вообще ни как. могу только кликнуть и камера откроется. Что я делаю не так?
![grkam](https://user-images.githubusercontent.com/13348933/185933952-bdd684f2-84e4-4f50-a813-72c279a1b56b.png)

**Comment by vladpen** [comment]
Попробуйте увеличить картинку.

**Comment by OmlineEditor** [comment]
мне не нужно увеличивать картинку, мне нужно переместить и поменять местами положени камер.

**Comment by vladpen** [comment]
Что-то мы в тупик зашли. Функционал увеличения для групп уже реализован, точно так же, как при просмотре одной камеры.

**Comment by OmlineEditor** [comment]
Да, у нас похоже тупик. Я про перемещение и замену камер местами, а вы мне про простое увеличение картинки говорите.

Я прошу реализовать возможность менять камеры местами в группе. Вот вы смотрите на телефон и сверху вниз у вас 4 камеры:
1 Калитка
2 Гараж
3 Двор
4 Вход в дом

И тут я хочу последнюю камеру переместить в списке выше и сделать так (см. картинку выше):
1 Калитка
4 Вход в дом
2 Гараж
3 Двор

Этого сейчас нет, я прошу это реализовать. Так понятно? мы вышли из тупика?

**Comment by vladpen** [comment]
Я говорю не про увеличение картинки, а про то, что увеличенная картинка перемещается по экрану.
Вероятно, вы хотите видеть на экране групп обработку "длинного нажатие" (long touch). Этот жест, теоретически, действительно можно было бы использовать для сортировки камер, но:

1. Если пользователь увеличит картинку настолько, что другие камеры будут не видны, куда ему перемещать текущую?
2. Пользователь не ожидает такого поведения. Сейчас экраны одной камеры и группы ведут себя абсолютно одинаково (за исключением одиночного нажатия для перехода к камере). Это логично.
3. Среднему пользователю не важен порядок. А если важен, его можно поменять в настройках группы. Вот там, действительно, не хватает сортировки камер, нужно бы добавить.
4. Потенциально возможны проблемы с производительностью на старых устройствах.

Почему вы хотите сортировать камеры именно тут?

**Comment by OmlineEditor** [comment]
> Вероятно, вы хотите видеть на экране групп обработку "длинного нажатие" (long touch). Этот жест, теоретически, действительно можно было бы использовать для сортировки камер, но:

Согласно, могут быть проблемы, нужно подумать как их обойти, пока только в голову приходит использовать "длинного нажатие" (long touch) не из одного пальца, а из двух.



> 1. Если пользователь увеличит картинку настолько, что другие камеры будут не видны, куда ему перемещать текущую?

А если сильно увеличил то нельзя перемещать камеры. водим запрет и все хорошо.


> 3\. Среднему пользователю не важен порядок.

А это не для среднего пользователя, средний пользователь думаю вообще вашу прогу не будет использовать, ваша прога для Гиков. Мне важен порядок, как и другим гикам любящим возможность тонкой настройки под себя, при наличии сортировке намного намного удобнее будет. 



> 2\. Сейчас экраны одной камеры и группы ведут себя абсолютно одинаково (за исключением одиночного нажатия для перехода к камере). Это логично.


Хорошо тогда откройте тикет и сделайте сортировки  в настройках, но вот как там сделать это https://github.com/vladpen/cams/issues/41 мне с трудом представляется.



> Почему вы хотите сортировать камеры именно тут?

Потому что это наглядно и понятно. намного понятнее чем в настройках при реализации этой функции https://github.com/vladpen/cams/issues/41 я думаю о будущем
