### ISSUE TITLE
Настройка по умолчанию для просмотра 1го или 2го потока

### ISSUE THREAD

**Issue by OmlineEditor** [vladpen/cams#44]
При просмотре в группе камер идет 2й поток, он очень маленький и его хватает для нормального непрерывного воспроизведения. У меня это примерно 256 (Кбит/с) с 5 камер = 1,25 (Мбит/с).
При переключении на одиночную камеру всегда идет 1й поток и нет варианта его переключить, нет варианта в настройках какой поток показывать (1й или 2й) при просмотре одиночной камеры.
Получается, что при нахождении в дальней комнате где плохо ловит Wi-Fi и низкая скорость, я не могу нормально смотреть одиночную камеры потому что не хватает полосы пропускания. Wi-Fi по скорости 5 Мбит/с, а первый поток с камеры больше и составляет 9 Мбит/с.
Аналогичная ситуация, когда я подключаюсь к камерам удаленно через VPN (его скорость от 5 Мбит/с до 10 Мбит/с) и иногда не получается также нормально смотреть 1й поток, но нормально идет 2й поток.

Иными словами, не всегда хватает полосы пропускания чтобы смотреть полноценно первый поток, я и любой другой пользователь кто отойдет от Wi-Fi подальше в дальнюю комнату или будет подключаться удаленно к камерам может столкнуться с проблемой, когда нет возможности посмотреть одиночную камеру вообще никак.

Поэтому прошу в настройках добавить пункт для камеры:
По умолчанию при просмотре камеры показывать: (и тут вариант выбора для пользователя 1й или 2й поток)

Так же при просмотре одиночной камеры прошу добавить кнопку для ручного переключения потока камеры.

**Comment by vladpen** [comment]
Вот это исчерпывающий комментарий к задаче, спасибо большое! Вот бы в энтерпрайзе так (мечтательно:)

Про полосу пропускания согласен, добавил переключатель каналов на экране камеры и сохранение последнего состояния аналогично выключению звука (уже на гитхабе). В дефолте для каждой камеры отдельно не вижу смысла, предлагаю следующую версию выпустить с этим функционалом.

**Comment by OmlineEditor** [comment]
Последнее состояние всегда сохраняется для любой камеры и всегда при выборе камеры будет именно последний поток использован, верно я поняла? Если да, то это еще лучше чем выбирать поток по умолчанию.

**Comment by vladpen** [comment]
Да, верно. Общий смысл в том, чтобы при просадке/восстановлении канала связи можно было оперативно переключить сразу все двухканальные камеры.

**Comment by OmlineEditor** [comment]
Я надеюсь переключение в ручном режиме происходит и программа сама не будет переключать ничего?

**Comment by vladpen** [comment]
Да, конечно.
