### ISSUE TITLE
Первый канал камеры явно пережат

### ISSUE THREAD

**Issue by OmlineEditor** [vladpen/cams#46]
При просмотре первого канала качество видео  явно не соответствует оригиналу. Вы зачем видео пережимаете?
Прошу показывать оригинал без пережатия.

P.S. Я не путаю первый и второй канал. второй канал еще хуже, так что ошибки быть не может.

![cams](https://user-images.githubusercontent.com/13348933/194883772-da27cf30-d41f-438e-a71a-88b2a875a740.jpg)
![real](https://user-images.githubusercontent.com/13348933/194883781-973b8fae-b226-43fb-8982-4319d4d6fedc.png)

**Comment by vladpen** [comment]
Сама программа ничего с потоками не делает, это может только камера. Значит, URL указан неверно. Например, мои камеры по адресу Channels/102/101 покажут канал низкого разрешения (см. [#48)](https://github.com/vladpen/cams/issues/48)

**Comment by OmlineEditor** [comment]
> Например, мои камеры по адресу Channels/102/101 покажут канал низкого разрешения

Все верно это второй канал у вас, а не первый, поэтому и низкого качества. нужно по адресу **_Channels/101_** смотреть.
У меня похожая проблема была пока не обрезала url

**Comment by OmlineEditor** [comment]
Прошу посмотреть что делает плагин VLC внутри программы т.е. если переключиться на 2й канал там даже кирпичей не видно, порсто коричневое месиво. Программа переключает каналы, 1й и 2й поток отличаются, но 1й почему-то не полный и пережатый.

**Comment by vladpen** [comment]
Чудес не бывает. Проверьте, пожалуйста, по логам, по какому URL подключается камера. И что будет, если убрать каналы (оставить один URL).

**Comment by OmlineEditor** [comment]
> что будет, если убрать каналы (оставить один URL).


Тоже самое, канал пережат и изображение не оригинльное. еще я заметила что пропорции изображения не верные в портретной ориентации телефона и в пейзажной, при повороте телефона меняется качество видео.

**Comment by OmlineEditor** [comment]
Судя по логам программа явно пережимает видео и уменьшает разрешение из-за какой-то ошибки
Исходное видео: 3840x2160, пережатое: 2432x1088
Ошибка:
libvlc window: request 1 not implemented
allocator 3.x is not supported
DequeueBuffer: dequeueBuffer failed
NdkMediaCodec: sf error code: -38

[logCam2.txt](https://github.com/vladpen/cams/files/9757401/logCam2.txt)

**Comment by vladpen** [comment]
2432x1088 это, случайно, не разрешение вашего устройства? Как вы вообще определили разрешение видео? Как воспроизводится эта камера этой же программой на других устройствах?

P.S. Насколько я вижу, 3840 / 2160 < 2432 / 1088. Могу предположить, что причина размытия именно в этом. Предлагаю проверить эту гипотезу.

**Comment by OmlineEditor** [comment]
> 2432x1088 это, случайно, не разрешение вашего устройства?

2432x1088 - на разрешение экрна ПОЧТИ похоже, оно немного отличается у меня 2340 x 1080.


> Как вы вообще определили разрешение видео?

по логам что выдала программа, возможно ошибаюсь.


> Как воспроизводится эта камера этой же программой на других устройствах?

намного лучше эта камера показывает на других устройствах, и если открыть в VLC на этом же устройстве и растянуть тогда касчество лучше чем в вашей программе.


вывод: сжатие есть и видео не оригинал, причина где-то внутри программы.

**Comment by vladpen** [comment]
> намного лучше эта камера показывает на других устройствах

Можете выразиться точнее - на других устройствах в этой же программе?

Предлагаю простой эксперимент:

1. Оставляем для этой камеры только 1-й канал
2. Создаем группу из двух камер: этой и любой другой с разрешением FullHD
3. Открываем группу, увеличиваем и смотрим на кирпичи. Заодно сравниваем размер в портретной и альбомной ориентации.

Если качество в норме и размеры фреймов совпали - ура, проблема концептуально решена, фиксируем размер фрейма на одиночном экране и выкатываем обновление. Если нет - всё плохо, разбираемся дальше.

P.S. В общем случае размытие не означает сжатие.

**Comment by vladpen** [comment]
Спасибо, понятно. Это про 4к камеру. А с обычными full HD проблем не было?

**Comment by OmlineEditor** [comment]
> А с обычными full HD проблем не было?

Точно сказать не могу, у меня нет таких камер. Тестировала на другой камере Full HD что временно дали доступ, там кажется все норм.

**Comment by vladpen** [comment]
Вердикт такой: на экране 2340x1080 увидеть 4к нельзя. Точнее, увеличивать картинку можно 3-мя способами:

1. Масштабировать экран
2. Увеличивать "поверхность" потока
3. Масштабировать "поверхность" потока

Сейчас реализован вариант 1, т.к. 2 и 3 требуют вмешательства в libVLC и, соответственно, приводят к снижению отзывчивости интерфейса и увеличению  потребления ресурсов процессора и памяти.

То есть в теории, если масштабировать сам поток, добиться лучшего качества увеличенного 4К на экране 2К можно, но платить за это будут пользователи обычных камер. Смысла в этом я не вижу и предлагаю для 4К просто рекомендовать использование устройств с высокой плотностью пикселей.

**Comment by vladpen** [comment]
Боюсь, пока старенькой бабушке придется страдать. Вариант №2 не выполним - андроид не справляется с увеличенной поверхностью даже 2К (хотя этот метод, действительно, даёт четкую картинку на любом экране), а для №3 в API нет методов перемещения. Очень жаль, конечно. Возможно, поможет [crop_window](https://videolan.videolan.me/vlc/group__libvlc__video.html#gaa001c1d652a7864759b6b6c52a9d6483), но это появится только в 4.0.

Предлагаю подождать.
