### ISSUE TITLE
Более интуитивно понятный способ указания каналов камеры

### ISSUE THREAD

**Issue by OmlineEditor** [vladpen/cams#48]
Сейчас я полову ломала как указать правильно два канала для камеры. У вас нужно указать только часть URL адреса и потом указать два числа как продолжение этого URL. Для многих это не явно и несовсем понятно. Еще нужно удалить часть старого URL чтобы все работало (удалить на конце допусим число /102 и потом отдельно указать 101 и 102 в новых полях).

Может как-то по другому сделать настройки или сделать приписку и пояснение, а то реально не понятно.

При наличии в адресе в конце /102 если ничего не удалять в основном поле и указании в отдельных новых полях 101 и 102, ничего не работает, каналы не пепереключаются. Прошу это учесть при обновлении настроек пользователем, допустим вы сами будите удалять часть URL.

**Comment by vladpen** [comment]
> ничего не работает, каналы не пепереключаются
первый (по порядку) указанный в URL канал должен работать, только не переключаться.

Вмешиваться в пользовательский ввод - плохая практика. Предлагаю, например, в случае совпадения одного из каналов с последней частью URL показать окно подтверждения типа "Адрес содержит номер канала. Продолжить?"

**Comment by OmlineEditor** [comment]
Для более интуитивно понятного ввода может проще указать два поля ввода, для 1го и 2го канала? А то сейсчас их три, основная ссылка и два поля для двух каналов.

А чтобы дважды не вводить пароль сделать отдельное поле для него https://github.com/vladpen/cams/issues/2

**Comment by vladpen** [comment]
Тоже думал об этом. У такого подхода есть и преимущества, и недостатки. Ставим задачу в низкий приоритет.

**Comment by OmlineEditor** [comment]
Поясните, какие вы видите недостатки?

**Comment by vladpen** [comment]
Главный плюс одного поля - это никогда не вызывает никаких вопросов. Люди просто копируют то, что указал производитель камеры, и всё работает.

Декомпозицию поля сделать можно, без проблем. Но если делать, нужно разбирать полностью на части. Но в этом случае усложняется интерфейс. Как минимум, все поля не влезут в экран - придется либо делать несколько, либо сдвинуть кнопку "Сохранить" вниз за пределы экрана. А если пользователь не найдёт кнопку или нужное ему поле, это вызовет вопросы. А я не хочу отвечать на вопросы такого рода. Имхо, интерфейс должен быть простым.

Сделать два поля адреса - заманчиво, конечно, но тогда пользователю придется копировать всю строку, включая IP и бестолковый путь типа "/ISAPI/Streaming/Channels". Это не очень "юзер френдли" и это источник неизбежных ошибок (начнут же руками набирать IP + порт + путь).

То, что есть сейчас, на мой вкус золотая середина - минимум ввода и, значит,  минимум возможностей ошибиться. Если не разобраться, что такое канал, просто будет работать тот, что в адресе (или первый в случае ошибки ввода). KISS же у нас)

**Comment by OmlineEditor** [comment]
> Как минимум, все поля не влезут в экран - придется либо делать несколько, либо сдвинуть кнопку "Сохранить" вниз за пределы экрана.

Добавьте новую кнопку на экран, см. скрин

![2](https://user-images.githubusercontent.com/13348933/195988787-e2ea1e52-06de-4cd4-997b-663b84f01711.jpg)



> Сделать два поля адреса - заманчиво, конечно, но тогда пользователю придется копировать всю строку, включая IP и бестолковый путь типа "/ISAPI/Streaming/Channels".

Не придется, 1 раз ввел 1й канал нажал кнопку 2й канал открывается 2е поле и данные в это поле копируется из 1го поля, пользователю нужно только поменять последнюю цифру, хотя вы автоматом можете при копировании это сделать.

С двумя полями понятнее, чем с тремя где сложным способом указавается части ссылки. Обязательно кто-то как я укажет **_не верно_** ссылку и будет смотреть только на один из каналов без возможности переключения. Далее отзывы типа: - _каналы не переключаются, ничего не работает 1 звезда, удаляю приложение_. Если следовать принципу KISS тогда нужно 2 поля, а не 3. Для проверки попросите человека кто мало знаком с вашим приложением верно указать **_с первого раза_** ссылки в ваши поля, ну это так для эксперимента.

**Comment by vladpen** [comment]
Тогда эту кнопку нужно вместо "Ещё" делать, и по ней открывать уже заполненное второе поле. Тут, правда, возникает масса вопросов, типа "а чем заполнять, если пользователь нажмет кнопку до заполнения адреса?".

Сверху - вообще не понятно, к чему это относится, похоже на "Сохранить" из конца 90-х.

В общем, тема не раскрыта.

**Comment by OmlineEditor** [comment]
> а чем заполнять, если пользователь нажмет кнопку до заполнения адреса

Ничем, поле просто копируется. У нас же принцип KISS. 
Внизу будет приписка:
_чтобы быстро заполнить 2е поле, заполините первое и нажмите кнопку дабавить 2е поле._

**Comment by vladpen** [comment]
Тогда, если нажать "добавить", второе поле будет каждый раз перезаписываться. Похоже, тут одной кнопкой не обойтись...

**Comment by OmlineEditor** [comment]
Опять вы проблемы на ровном месте сами себе создаете.
2го поля по умолчанию нет, но есть кнопка "использовать 2 канала".
нажимаем кнопку, поля копируются и кнопка "использовать 2 канала" исчезает и в другом месте и точнее рядом в с полем 2го канала появляется кнопка удаления этого канала. Всё просто.

![2_edit_ru](https://user-images.githubusercontent.com/13348933/196191309-ce5e2a06-c1b0-429e-8102-4fba645dae5e.jpg)
![2_edit_ru2](https://user-images.githubusercontent.com/13348933/196191332-54c02025-a3f9-427b-b32d-8c3a9ff425f3.jpg)

**Comment by vladpen** [comment]
Выполнено. После обновления каналы нужно будет добавить вручную, укажу в ченйнджлоге следующей версии.
