### ISSUE TITLE
Убрать поле с названием камеры и стрелкой в пейзажной ориентации

### ISSUE THREAD

**Issue by OmlineEditor** [vladpen/cams#5]
При просмотре камеры в портретной ориентации проблем нет, верхняя строка с названием камеры и стрелкой не мешает, а вот если перевернуть и смотреть в пейзажной ориентации тогда эта строка загораживает часть видео и еще она полупрозрачная и немного затемняет видео, ее заметно и она мешает просмотру.
Прошу ее скрыть в пейзажной ориентации или добавить в настройки опцию скрывать в пейзажной ориентации строку с названием камеры или нет.

![screens](https://user-images.githubusercontent.com/13348933/160438082-7999a67a-6379-4fdf-95e9-73e37c756bbe.png)

**Comment by vladpen** [comment]
Добавлено автоскрытие панелей.
