### ISSUE TITLE
Нет мастабирования в Android 6

### ISSUE THREAD

**Issue by OmlineEditor** [vladpen/cams#51]
Открываю камеру в Android 6, старенький планшет. Пытаюсь изменить масшатаб камеры приблизить, но ничего не приближается и видео просто переезжает в левый вехний угол, т.е. просто катается по диагонали туда-сюда без мастабирования.

**Comment by vladpen** [comment]
Предполагаю, что в libvlc сломана обратная совместимость виджета VideoLayout с Marshmallow (скорее всего, что-то не так с трассировкой событий). Пришлось поднять минимальную версию андроида до 7 (Nougat), увы. Пулл реквесты принимаются)

**Comment by OmlineEditor** [comment]
Может тогда написать разработчикам libvlc и казать что там есть пролема. Вы можете им написать и пояснить что там не так? Вы в этом разбираетесь и понимаете в отличии от меня.

Я думаю пользователей 6-го анроида еще много в мире и они сильно огорчатся что не смогут использовать вашу программу. Старый планшет на 6-м андроиде для просмотра камер отлично подходит. Не лишайте людей возможности смотреть камеры.

**Comment by vladpen** [comment]
Я написал, еще на прошлой неделе. Молчат пока. Предлагаю подождать.

P.S. Смотреть камеры можно, проблема только с увеличением.

**Comment by OmlineEditor** [comment]
> P.S. Смотреть камеры можно, проблема только с увеличением.

Да все верно, нельзя только увеличить, поэтому прошу пока не повышать минимальную версию андроида до 7й.

**Comment by vladpen** [comment]
Повышение версии не отключит старые модели, только выдаст предупреждение при установке, что, в нашем случае, соответствует действительности. Если этот вопрос сдвинется с мертвой точки, вернем обратно.

**Comment by OmlineEditor** [comment]
Старые версии программы будут работать, но новую версию люди просто **_не смогут_** поставить если минимальная версия Android 7, а у них Android 6.

**Comment by vladpen** [comment]
Я пытаюсь решить проблему доставки потоков большему количеству пользователей, работы ведутся.

В любом случае, предлагать людям заведомо неработающий функционал нечестно.
И, в любом случае, поменять одну цифру в конфигурации может любой желающий - у нас же open source.
И, к сожалению, поддержка старых версий всегда будет прекращаться по мере выхода новых, и не только в Андроиде - это везде так.

**Comment by OmlineEditor** [comment]
> поменять одну цифру в конфигурации может любой желающий - у нас же open source.

Вы переоцениваете возможности обычных пользователей, не все смогут скомпилировать приложение и найти место где нужно поменять эту цифру.

**Comment by vladpen** [comment]
Могу предложить раздавать APK для старых моделей в отдельной ветке, например.

**Comment by OmlineEditor** [comment]
Идея хорошая но как быть людям которые скачивают вашу программу с f-droid или с rustore?
Может пусть будет для всех минимальная версия андроида 4.4, да там нет масштабирования но есть возможность смотреть картинку с камер. Это лучше чем ничего или отдельная ветка про которую знают 3 человека (Вы, я и дадя Толя программист).

**Comment by vladpen** [comment]
Тогда нужно удалить пункт про увеличение и заблокировать функционал в коде для старых версий. Это костыль, противоречащий принципам open source и KISS. И, кстати, ниже 6-й версии опускаться все равно нельзя, линтер будет ругаться.

**Comment by OmlineEditor** [comment]
Из двух зол выбирайте  меньшее:
- не работает совсем и даже нельзя поставить на старый андроид, нужно идти покупать новый телефон или планшет.
- поставить ВРЕМЕННЫЙ костыль для старой версии и всё работает и все счастливы.
