### ISSUE TITLE
Полное шифрование экспортированных данных

### ISSUE THREAD

**Issue by OmlineEditor** [vladpen/cams#52]
Прошу сделать возможность **_полностью_** шифровать бэкап, а не только пароль.
Если я загружу данные в облако или бэкап кто-то крадет он увидит, логины, IP адреса и порт, которые я так старательно меняла.
Имена камер и внутреняя структура сети долна быть защищена.
Релизация алгоритма AES и base64 помогут в этом деле.

**Comment by vladpen** [comment]
Не очень понятен смысл делать это именно в плеере. Данные же файлом отдаются, их можно шифровать, как угодно. У вас же не один такой файл в бекапах хранится.

P.S. Шифровать всегда целиком не вариант, в большинстве случаев файл нужен в открытом виде.

**Comment by OmlineEditor** [comment]
Я надеюсь вы меня правильно поняли. нужно шифровать файл бэкапа, тот что куда-то может быть передан. Для шифроваки этого файла чем-то стороним нужна доп. программа это не удобно. Нужно чтобы бэкап файла был скрыт полностью и если его кто-то перехватит он не узнает внуреннее строенее сети, количесво камер и их название и не сможет утроить взлом пароля камеры если узнает логин.

**Comment by vladpen** [comment]
Да, я вас понял. Но если экстраполировать эту мысль, пусть тогда плеер и данные других программ шифрует (не все же умеют это делать), а заодно и сам синхронизирует их. Тут правда начнут возникать вопросы типа "А куда это ваша программа мои данные сливает?" Учитывая текущую геополитическую обстановку, ну очень популярный вопрос.

Имхо, хранение и шифрование бекапов выходит далеко за рамки полномочий проигрывателя. Плюс вы предлагаете заставить пользователя еще один пароль выдумывать - это плохой подход, не любят они этого)

**Comment by OmlineEditor** [comment]
Так, стоп. Кто-то у нас тут не верно понял кого-то. Кажется это я. Извините, щас поправлюсь. Я называю экспортированные данные - бэкапом (наверное потому что сразу их складываю в папку /backup/cams/).
Когда я делаю экспор данных, у меня появляется файл бэкапа который в текстровом виде никак не зашифрован (только пароль зашифрован). Когда я делаю этот бэкап я уже ввожу пароль, этот пароль и должен шифровать все экспортированные данные.

Меняем, тему на: Полное шифрование **_экспортированных данных_**

**Comment by vladpen** [comment]
Тогда предлагаю в диалоге сохранения сделать переключатель вида "Без шифрования - Шифровать только пароль - Шифровать файл целиком".

**Comment by OmlineEditor** [comment]
Не, это перебор. У нас принцип KISS и спрашивать пользователя о чем он с трудом понимает, думаю не следует. Просто если указываем пароль тогда шифруем файл целиком и точка. У нас там важные приватные данные и без шифрования хранить их опасно.

**Comment by vladpen** [comment]
Выполнено. Экспорт нужно выполнить заново (после перевода каналов на новую схему хранения, см. [#48),](https://github.com/vladpen/cams/issues/48) обратной совместимости нет.
