### ISSUE TITLE
Remove the No Wi-Fi message on a working stream

### ISSUE THREAD

**Issue by rainniel** [vladpen/cams#65]
I have an internal-only IP camera and a VPN server in my home network, while connected to any wifi connection, the No Wi-Fi message don't appear. When I go outside, I access the IP camera via my VPN server on mobile data connection, while successfully connected to the stream, there's a No Wi-Fi message under it, please remove that message on a working stream, and when it fails to connect, maybe just change it to connection failed or any similar error message.

![Screenshot_20230610_101439_Cams](https://github.com/vladpen/cams/assets/8403974/e56500ac-7f09-4c20-97c3-361a82b19412)

Thanks.

**Comment by vladpen** [comment]
Fixed in 2.0.3.

Thanks for reporting the bug.
