### ISSUE TITLE
Neos SmartCam

### ISSUE THREAD

**Issue by Savasdotexe** [vladpen/cams#67]
Hi, I've got a Neos SmartCam and I'm unable to successfully add the camera.

I was able to add it on tinyCam Monitor (app on the play store) so I'm wondering if I'm missing something on Cams or if there's anyway I can pull the correct URL over?

**Comment by vladpen** [comment]
Hi.
Are you able open this camera in VLC app?
Also provide a sample of your URL here, please.

**Comment by Savasdotexe** [comment]
> Hi. Are you able to open this camera in VLC app? Also provide a sample of your URL here, please.

Unfortunately, no I've had no luck opening it on VLC app.

I could be completely mistaken, but I do recall managing to open this on Cams by copying the URL from tinyCam Monitor app which I had selected as a Wyze device, however when I reset my phone I had to add the camera again on that as I could not figure it out until I chose the "Cloud" protocol. I can't seem to find where to get the working URL from within tinyCam monitor to share that with.

I think I was using something like (but I could be mistaking it with something else to be honest):

rtsp://192.168.0.200/unicast
rtsp://192.168.0.200:8554/unicast
rtsp://192.168.0.200:554/live

**Comment by vladpen** [comment]
Okay, then you can take a look at the connection logs to understand what's going on. This log is disabled for security reasons, but you can temporarily enable it in the "About - Logs" section. After that, you should immediately try to connect, and then return to viewing the logs again.

Also you can try to find the correct URL format in your camera docs.
