### ISSUE TITLE
Не верное поведение кнопки назад

### ISSUE THREAD

**Issue by OmlineEditor** [vladpen/cams#7]
Для повторение ошибки:
- открываю программу
- Жму настрока на одной из камер
- меняю название камеры
- сохраняю (переходит в основное окно)
- кликаю на камеру для просмотра 
- кликаю назад для перехода назад в основное меню (все норм перехожу)
- кликаю еще раз назад чтобы выйти (в место этого попадаю в настройки камеры где меняла название)
- кликаю еще раз назад переходит в основное меню и я там с удивлением вижу название камеры до ее переименования
- кликаю назад 3 раз и наконец то выхожу из программы (если менять название и заходить в настройки не одной, а нескольких камер тогда нажимая назад я буду ходить по всем этим камерам в обратной последовательности и только потом выйду из программы)

Тут все кнопки **_назад_** это те что у андроида внизу где **_треугольник_**, круг и квадрат.

**Comment by vladpen** [comment]
Спасибо, исправлено.
