### ISSUE TITLE
It is not clear which channel is being used when in a group

### ISSUE THREAD

**Issue by MalakymR** [vladpen/cams#72]
When a stream is added to a group, it is not clear which channel is being used and there is no choice when adding the cameras to the group.

It also seems most likely to use C2, but not consistently.

**Comment by vladpen** [comment]
Currently groups always try to use a second channel if available. This is done to simplify the interface.

But this may really be unnecessary with a fast internet connection.

Therefore I suggest adding a channel switch on the group screens, like on the standalone camera screens, for manual switching.

**Comment by MalakymR** [comment]
That's a good idea that the lowest quality stream is used in groups/montages - though I use the first one as my low quality stream and switch to high as and when I need it.

Not really about speed - but the delay when it first comes up - specially on mobile networks.

**Comment by vladpen** [comment]
Channel switcher on group screens added in v2.2.

Thanks for your feedback!
