### ISSUE TITLE
Support for renaming channels

### ISSUE THREAD

**Issue by robbie99us** [vladpen/cams#73]
Hi there! Your app has been of such utility for me, thanks for all your work :)
Would it be difficult to implement an option to rename the channels? For example, I have 8 EZVIZ cameras, working fine with your app. However I just realized that those cameras have a low quality stream and a high quality stream, which is great! So I added the lower quality channel to each stream on the app.  But it's kinda difficult to remember which "C1" or "C0" is the low quality or the high quality stream.
Being able to rename "C0" or "C1" to "Low quality" or "LQ" or something else would make it easier to use the app.
Thanks!

**Comment by vladpen** [comment]
Hi!

You're right, C0/C1 is a bad user interface. Now I have replaced this button with a channel icon, it will be available in the next version.

Thank you for your feedback. Good luck!
