### ISSUE TITLE
Failing camera not detected, no auto-reconnect, no connect during camera startup

### ISSUE THREAD

**Issue by abzmr** [vladpen/cams#74]
Thanks for the very nice app, which has exactly the features and simplicity that we like!

Now one of our cameras has become somewhat unstable, and is rebooting every few days. Unfortunately, the Cams app is not detecting that, and it will keep showing the last image from just before the reboot. Since the camera points to a relatively unused area, it will often not be noticed that the Cams app is still showing an image of many hours ago, instead of the live video feed that has only been interrupted for less than a minute.

We tried with VLC, and this is properly detecting lost contact after 10 seconds.

We suggest that you could at least detect any lost contact just like VLC does, and either blank that camera display or put a big fat warning on it.

Then, ideally, you could keep reconnecting to that camera, until it comes online again.

This turns out to be an issue at startup as well: our camera takes some 35 seconds to boot up, and if we start the Cams app during that time, the loading bar will just keep running, and it will never connect to the camera even when the camera is running again. So that could probably also use some attention.

Thanks again, and keep up the good work!

**Comment by vladpen** [comment]
Hello!

The Cams app now has a watchdog instead of the network observer. Additionally, if the connection to one or more cameras is lost, a loading indicator is displayed. Hope this solves the problem. The fix will be available after version 2.3 is released.

Thanks for your research!

**Comment by abzmr** [comment]
That's very good news, and really quick too :)   I'm looking forward to the 2.3 release!
