### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by Quantum-Future** [vladpen/cams#76]
I upgraded to Ver 2.3 but I don't know how to put the icons introduced in this version.
(I don't see where to select the icons).

**Comment by vladpen** [comment]
New system icons replace the uninformative channel switch (see #73 for details). You don't need to do anything.

**Comment by Quantum-Future** [comment]
Sorry but I don't understand. 
I have only one camera with one channel, and no icon is shown.
I added a 2nd channel and no icon shown.
Then I added a 2nd camera and no icon is shown.

The icons should appear automatically or the user can select which icon to show?

**Comment by vladpen** [comment]
Then I didn’t understand you, and the documentation is not clear enough. The camera icon isn't really an icon, it's just an emoji. In the "camera name" field you can select any suitable emoji from the set available on your device. I'll try to add some notice to the description.

**Comment by Quantum-Future** [comment]
Aahh... Ok !   Now I understand.
