### ISSUE TITLE
Добавить вывод логов

### ISSUE THREAD

**Issue by OmlineEditor** [vladpen/cams#8]
Прошу сделать возможность видеть логи об ошибках если таковые имеются. Подключаюсь к камерам но что-то не так и не работает камера. А вот понять что именно не так без показа логов нельзя. Добавьте вывод логов для удобства.

**Comment by OmlineEditor** [comment]
Без логов совсем все печально и не понятно что происходит.
При переустановке программы есть глюк с одной камерой.
То работает то не работает, понять без логов не возможно, прошу сделать отдельное окно куда будут выводится все логи или поиск ошибок сильно затянется.

**Comment by vladpen** [comment]
Добавлено в раздел "О программе".

Для логирования подключения к камере нужно предварительно поставить галочку в диалоговом окне. Так как сохранение этой информации в журнале потенциально опасно, настройка сохраняется только до закрытия приложения.

**Comment by OmlineEditor** [comment]
Эту пояснительную информацию вы сделали рядом с галочкой? Ну чтобы другие люди знали и понимали что и как нужно делать?

**Comment by vladpen** [comment]
Да, все уже в гите и в сборке на гитхабе.
